import express from "express";
import path from "path";
import fs from "fs";
import { spawn, ChildProcess } from "child_process";
import { GoogleGenAI, ThinkingLevel } from "@google/genai";
import dotenv from "dotenv";
import { VideoMetadata, DownloadItem, HistoryRecord, UserSettings, FormatInfo } from "./src/types.js";

dotenv.config();

const app = express();
const PORT = 3000;

// Shared Gemini initialization
const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
  httpOptions: {
    headers: {
      'User-Agent': 'aistudio-build',
    }
  }
});

// Paths for persistence
let DATA_DIR = path.join(process.cwd(), "data");
let DOWNLOADS_DIR = path.join(DATA_DIR, "downloads");
let HISTORY_FILE = path.join(DATA_DIR, "history.json");
let SETTINGS_FILE = path.join(DATA_DIR, "settings.json");
let COOKIES_FILE = path.join(DATA_DIR, "cookies.txt");

// Ensure directories exist
try {
  if (!fs.existsSync(DATA_DIR)) {
    fs.mkdirSync(DATA_DIR, { recursive: true });
  }
  if (!fs.existsSync(DOWNLOADS_DIR)) {
    fs.mkdirSync(DOWNLOADS_DIR, { recursive: true });
  }
} catch (err) {
  console.warn("Unable to create data directories in current working directory. Falling back to /tmp/data for serverless environments:", err);
  DATA_DIR = "/tmp/data";
  DOWNLOADS_DIR = path.join(DATA_DIR, "downloads");
  HISTORY_FILE = path.join(DATA_DIR, "history.json");
  SETTINGS_FILE = path.join(DATA_DIR, "settings.json");
  COOKIES_FILE = path.join(DATA_DIR, "cookies.txt");
  try {
    if (!fs.existsSync(DATA_DIR)) {
      fs.mkdirSync(DATA_DIR, { recursive: true });
    }
    if (!fs.existsSync(DOWNLOADS_DIR)) {
      fs.mkdirSync(DOWNLOADS_DIR, { recursive: true });
    }
  } catch (tmpErr) {
    console.error("Failed to create fallback temporary directories:", tmpErr);
  }
}

// In-memory state for active downloads
const activeDownloads = new Map<string, DownloadItem>();
const activeProcesses = new Map<string, ChildProcess>();

// SSE clients for real-time progress stream
let sseClients: any[] = [];

// Helper to save history
const getHistory = (): HistoryRecord[] => {
  if (fs.existsSync(HISTORY_FILE)) {
    try {
      return JSON.parse(fs.readFileSync(HISTORY_FILE, "utf8"));
    } catch (e) {
      return [];
    }
  }
  return [];
};

const saveHistory = (history: HistoryRecord[]) => {
  fs.writeFileSync(HISTORY_FILE, JSON.stringify(history, null, 2), "utf8");
};

// Helper to save/load settings
const getSettings = (): UserSettings => {
  const defaultSettings: UserSettings = {
    theme: "dark",
    defaultQuality: "1080p",
    defaultFolder: DOWNLOADS_DIR,
    proxy: "",
    language: "en",
    autoUpdate: false,
    maxSimultaneousDownloads: 3,
    fallbackNearest: true,
    cookies: "",
  };

  if (fs.existsSync(SETTINGS_FILE)) {
    try {
      const parsed = JSON.parse(fs.readFileSync(SETTINGS_FILE, "utf8"));
      const merged = { ...defaultSettings, ...parsed };
      if (merged.proxy) {
        const p = merged.proxy.toLowerCase().trim();
        if (p.includes("youtube.com") || p.includes("youtu.be") || p === "http://" || p === "https://") {
          merged.proxy = "";
        }
      }
      return merged;
    } catch (e) {
      return defaultSettings;
    }
  }
  return defaultSettings;
};

const convertToNetscapeCookies = (rawInput: string): string => {
  const trimmed = rawInput.trim();
  if (!trimmed) return "";

  // 1. Check if it is already in Netscape format or has tab-separated values
  const lines = trimmed.split(/\r?\n/);
  const hasTabs = lines.some(line => {
    const p = line.split("\t");
    return p.length >= 6 && !isNaN(Number(p[4]));
  });

  if (hasTabs || trimmed.startsWith("# Netscape") || trimmed.startsWith("# HttpOnly")) {
    if (!trimmed.startsWith("# Netscape")) {
      return "# Netscape HTTP Cookie File\n# This file was generated by YT_CORE\n" + trimmed;
    }
    return trimmed;
  }

  // 2. Check if it is JSON format (e.g. from EditThisCookie or similar extensions)
  if (trimmed.startsWith("[") && trimmed.endsWith("]")) {
    try {
      const parsed = JSON.parse(trimmed);
      if (Array.isArray(parsed)) {
        let netscape = "# Netscape HTTP Cookie File\n# This file was generated by YT_CORE\n";
        let count = 0;
        for (const item of parsed) {
          if (item && typeof item === "object" && item.name && item.value !== undefined) {
            const domain = item.domain || ".youtube.com";
            const includeSubdomains = domain.startsWith(".") ? "TRUE" : "FALSE";
            const path = item.path || "/";
            const secure = item.secure ? "TRUE" : "FALSE";
            const expiry = Math.floor(item.expirationDate || item.expiry || (Date.now() / 1000 + 365 * 24 * 3600));
            netscape += `${domain}\t${includeSubdomains}\t${path}\t${secure}\t${expiry}\t${item.name}\t${item.value}\n`;
            count++;
          }
        }
        if (count > 0) {
          return netscape;
        }
      }
    } catch (e) {
      // Failed parsing as JSON, proceed to raw Cookie header parse
    }
  }

  // 3. Fallback: Parse as a raw Cookie request header or semicolon-separated name=value pairs
  // e.g. "Cookie: name1=value1; name2=value2" or just "name1=value1; name2=value2"
  let cookieString = trimmed;
  if (cookieString.toLowerCase().startsWith("cookie:")) {
    cookieString = cookieString.slice(7).trim();
  }

  const parts = cookieString.split(";");
  let netscape = "# Netscape HTTP Cookie File\n# This file was generated by YT_CORE\n";
  let count = 0;

  for (const part of parts) {
    const trimmedPart = part.trim();
    if (!trimmedPart) continue;
    const eqIdx = trimmedPart.indexOf("=");
    if (eqIdx > 0) {
      const name = trimmedPart.slice(0, eqIdx).trim();
      const value = trimmedPart.slice(eqIdx + 1).trim();
      if (name && value) {
        // Far future expiration (5 years from now)
        const expiry = Math.floor(Date.now() / 1000 + 5 * 365 * 24 * 3600);
        netscape += `.youtube.com\tTRUE\t/\tTRUE\t${expiry}\t${name}\t${value}\n`;
        count++;
      }
    }
  }

  if (count > 0) {
    return netscape;
  }

  return rawInput;
};

const saveSettings = (settings: UserSettings) => {
  if (settings.proxy !== undefined) {
    const p = settings.proxy.toLowerCase().trim();
    if (p.includes("youtube.com") || p.includes("youtu.be") || p === "http://" || p === "https://") {
      settings.proxy = "";
    } else {
      settings.proxy = settings.proxy.trim();
    }
  }

  if (settings.cookies !== undefined && settings.cookies.trim()) {
    settings.cookies = convertToNetscapeCookies(settings.cookies);
  }

  fs.writeFileSync(SETTINGS_FILE, JSON.stringify(settings, null, 2), "utf8");

  if (settings.cookies !== undefined) {
    if (settings.cookies.trim()) {
      fs.writeFileSync(COOKIES_FILE, settings.cookies, "utf8");
    } else if (fs.existsSync(COOKIES_FILE)) {
      try {
        fs.unlinkSync(COOKIES_FILE);
      } catch (e) {
        // ignore
      }
    }
  }
};

// Sync cookies file on startup
try {
  const settings = getSettings();
  if (settings.cookies && settings.cookies.trim()) {
    fs.writeFileSync(COOKIES_FILE, settings.cookies, "utf8");
  }
} catch (e) {
  console.error("Failed to sync cookies on startup:", e);
}

// Helper to notify all SSE clients of changes
const notifyProgressClients = () => {
  const payload = JSON.stringify(Array.from(activeDownloads.values()));
  sseClients.forEach((client) => {
    client.write(`data: ${payload}\n\n`);
  });
};

app.use(express.json());

// API: Get settings
app.get("/api/settings", (req, res) => {
  res.json(getSettings());
});

// API: Save settings
app.post("/api/settings", (req, res) => {
  const settings = req.body as UserSettings;
  saveSettings(settings);
  res.json({ success: true, settings });
});

// API: Get history
app.get("/api/history", (req, res) => {
  res.json(getHistory());
});

// API: Clear history
app.delete("/api/history", (req, res) => {
  saveHistory([]);
  res.json({ success: true });
});

// API: Parse Video Info
app.get("/api/info", (req, res) => {
  const url = req.query.url as string;
  if (!url) {
    return res.status(400).json({ error: "URL is required" });
  }

  const runInfoQuery = (useCookies: boolean) => {
    const settings = getSettings();
    const infoArgs = [
      "--dump-json", 
      "--no-playlist", 
      "--extractor-args", "youtube:player_client=android,mweb,web", 
      "--js-runtimes", "node",
      "--remote-components", "ejs:github"
    ];
    if (settings.proxy) {
      infoArgs.push("--proxy", settings.proxy);
    }
    if (useCookies && fs.existsSync(COOKIES_FILE)) {
      infoArgs.push("--cookies", COOKIES_FILE);
    }
    infoArgs.push(url);

    const ytDlp = spawn("yt-dlp", infoArgs, { env: { ...process.env, PYTHONWARNINGS: "ignore" } });

    let stdoutData = "";
    let stderrData = "";
    let handled = false;

    ytDlp.stdout.on("data", (data) => {
      stdoutData += data.toString();
    });

    ytDlp.stderr.on("data", (data) => {
      stderrData += data.toString();
    });

    ytDlp.on("error", (err: any) => {
      if (handled) return;
      handled = true;
      console.error("yt-dlp info spawn error:", err);
      let errMsg = "Failed to run yt-dlp on the server. Please ensure yt-dlp is installed and in the system's PATH.";
      if (err.code === "ENOENT") {
        errMsg = "The yt-dlp binary was not found on this server. If you deployed this application on Vercel, please note that Vercel is a stateless, serverless environment that does not support running custom CLI binaries or background Python processes like yt-dlp. Please deploy this application to a persistent container/VM platform like Google Cloud Run, Railway, Render, or a VPS.";
      }
      res.status(500).json({ error: errMsg, details: err.message });
    });

    ytDlp.on("close", (code) => {
      if (handled) return;
      handled = true;
      const cleanedStderr = stderrData
        .split("\n")
        .filter(line => !line.includes("Support for Python version 3.10 has been deprecated") && !line.includes("Deprecated Feature: Support for Python"))
        .join("\n")
        .trim();

      const isCookieInvalid = cleanedStderr.includes("cookies are no longer valid") || 
                            cleanedStderr.includes("The provided YouTube account cookies are no longer valid") ||
                            cleanedStderr.includes("rotated in the browser as a security measure");

      if (code !== 0) {
        if (useCookies && isCookieInvalid) {
          console.warn("[Self-Healing] Detected expired/invalid YouTube cookies in info query. Clearing cookies and retrying without cookies...");
          
          try {
            if (fs.existsSync(COOKIES_FILE)) {
              fs.unlinkSync(COOKIES_FILE);
            }
          } catch (e) {}

          const currentSettings = getSettings();
          currentSettings.cookies = "";
          saveSettings(currentSettings);

          // Retry immediately
          return runInfoQuery(false);
        }

        console.error("yt-dlp info error:", cleanedStderr);
        let userFriendlyError = "Failed to load video info.";
        if (cleanedStderr.includes("Incomplete YouTube ID")) {
          userFriendlyError = "Invalid YouTube URL.";
        } else if (cleanedStderr.includes("Private video")) {
          userFriendlyError = "This is a private video and cannot be downloaded.";
        } else if (cleanedStderr.includes("The page could not be found") || cleanedStderr.includes("NOT_FOUND") || cleanedStderr.includes("not found")) {
          userFriendlyError = "The requested video could not be found. Please make sure the URL is correct and the video is public.";
        } else if (isCookieInvalid) {
          userFriendlyError = "Your YouTube cookies have expired or been rotated. Please open YouTube in your browser, export brand-new cookies, paste them in the Settings tab, and click Save.";
        } else if (cleanedStderr.includes("Sign in to confirm your age")) {
          userFriendlyError = "This video is age-restricted and requires authentication.";
        } else if (cleanedStderr.includes("Unable to download webpage")) {
          userFriendlyError = "Network error or invalid link. Please try again.";
        } else if (cleanedStderr.includes("confirm you’re not a bot") || cleanedStderr.includes("confirm you're not a bot") || cleanedStderr.includes("Sign in to confirm")) {
          userFriendlyError = "YouTube is requesting verification to confirm you are not a bot. Please go to the Settings tab and paste your Netscape-format YouTube cookies to authenticate your requests.";
        }
        return res.status(500).json({ error: userFriendlyError, details: cleanedStderr });
      }

      try {
        const json = JSON.parse(stdoutData);
      
      // Map formats
      const formats: FormatInfo[] = (json.formats || []).map((f: any) => {
        let type: 'video' | 'audio' | 'combined' = 'combined';
        if (f.vcodec !== 'none' && f.acodec === 'none') type = 'video';
        if (f.vcodec === 'none' && f.acodec !== 'none') type = 'audio';

        const hasHdr = f.dynamic_range && f.dynamic_range.toLowerCase().includes("hdr");

        return {
          formatId: f.format_id,
          ext: f.ext,
          resolution: f.resolution || (f.width && f.height ? `${f.width}x${f.height}` : null) || (f.vcodec !== 'none' ? "Video" : "Audio"),
          height: f.height || null,
          fps: f.fps || null,
          codec: f.vcodec !== 'none' ? f.vcodec : f.acodec,
          bitrate: f.tbr || null,
          fileSize: f.filesize || f.filesize_approx || null,
          type,
          hdr: hasHdr ? f.dynamic_range : undefined,
          vcodec: f.vcodec && f.vcodec !== 'none' ? f.vcodec : undefined,
          acodec: f.acodec && f.acodec !== 'none' ? f.acodec : undefined,
          asr: f.asr || undefined,
          audioChannels: f.audio_channels || undefined
        };
      });

      // Map subtitles
      const subtitles: string[] = [];
      if (json.subtitles) {
        subtitles.push(...Object.keys(json.subtitles));
      }
      if (json.automatic_captions) {
        subtitles.push(...Object.keys(json.automatic_captions).map(k => `${k} (auto)`));
      }

      const metadata: VideoMetadata = {
        url,
        id: json.id,
        title: json.title,
        channel: json.uploader || json.channel || "Unknown Channel",
        duration: json.duration || 0,
        thumbnail: json.thumbnail || (json.thumbnails && json.thumbnails[0]?.url) || "",
        uploadDate: json.upload_date ? `${json.upload_date.substring(0, 4)}-${json.upload_date.substring(4, 6)}-${json.upload_date.substring(6, 8)}` : "Unknown Date",
        description: json.description || "",
        viewCount: json.view_count || 0,
        formats,
        subtitles: Array.from(new Set(subtitles)),
        isPlaylist: false
      };

      res.json(metadata);
    } catch (e) {
      console.error("JSON parsing error:", e);
      res.status(500).json({ error: "Failed to parse video metadata.", details: e });
    }
    });
  };

  runInfoQuery(true);
});

// API: Detect and Get Playlist Info
app.get("/api/playlist-info", (req, res) => {
  const url = req.query.url as string;
  if (!url) {
    return res.status(400).json({ error: "URL is required" });
  }

  const runPlaylistQuery = (useCookies: boolean) => {
    const settings = getSettings();
    const playlistArgs = [
      "--flat-playlist", 
      "--dump-json", 
      "--extractor-args", "youtube:player_client=android,mweb,web", 
      "--js-runtimes", "node",
      "--remote-components", "ejs:github"
    ];
    if (settings.proxy) {
      playlistArgs.push("--proxy", settings.proxy);
    }
    if (useCookies && fs.existsSync(COOKIES_FILE)) {
      playlistArgs.push("--cookies", COOKIES_FILE);
    }
    playlistArgs.push(url);

    const ytDlp = spawn("yt-dlp", playlistArgs, { env: { ...process.env, PYTHONWARNINGS: "ignore" } });

    let stdoutData = "";
    let stderrData = "";
    let handled = false;

    ytDlp.stdout.on("data", (data) => {
      stdoutData += data.toString();
    });

    ytDlp.stderr.on("data", (data) => {
      stderrData += data.toString();
    });

    ytDlp.on("error", (err: any) => {
      if (handled) return;
      handled = true;
      console.error("yt-dlp playlist spawn error:", err);
      let errMsg = "Failed to run yt-dlp on the server. Please ensure yt-dlp is installed and in the system's PATH.";
      if (err.code === "ENOENT") {
        errMsg = "The yt-dlp binary was not found on this server. If you deployed this application on Vercel, please note that Vercel is a stateless, serverless environment that does not support running custom CLI binaries or background Python processes like yt-dlp. Please deploy this application to a persistent container/VM platform like Google Cloud Run, Railway, Render, or a VPS.";
      }
      res.status(500).json({ error: errMsg, details: err.message });
    });

    ytDlp.on("close", (code) => {
      if (handled) return;
      handled = true;
      const cleanedStderr = stderrData
        .split("\n")
        .filter(line => !line.includes("Support for Python version 3.10 has been deprecated") && !line.includes("Deprecated Feature: Support for Python"))
        .join("\n")
        .trim();

      const isCookieInvalid = cleanedStderr.includes("cookies are no longer valid") || 
                            cleanedStderr.includes("The provided YouTube account cookies are no longer valid") ||
                            cleanedStderr.includes("rotated in the browser as a security measure");

      if (code !== 0) {
        if (useCookies && isCookieInvalid) {
          console.warn("[Self-Healing] Detected expired/invalid YouTube cookies in playlist query. Clearing cookies and retrying without cookies...");
          
          try {
            if (fs.existsSync(COOKIES_FILE)) {
              fs.unlinkSync(COOKIES_FILE);
            }
          } catch (e) {}

          const currentSettings = getSettings();
          currentSettings.cookies = "";
          saveSettings(currentSettings);

          // Retry immediately
          return runPlaylistQuery(false);
        }

        console.error("yt-dlp playlist error:", cleanedStderr);
        let userFriendlyError = "Failed to parse playlist details.";
        if (cleanedStderr.includes("Incomplete YouTube ID")) {
          userFriendlyError = "Invalid YouTube URL.";
        } else if (cleanedStderr.includes("Private video")) {
          userFriendlyError = "This is a private playlist and cannot be parsed.";
        } else if (cleanedStderr.includes("The page could not be found") || cleanedStderr.includes("NOT_FOUND") || cleanedStderr.includes("not found")) {
          userFriendlyError = "The requested playlist could not be found. Please make sure the URL is correct and the playlist is public.";
        } else if (isCookieInvalid) {
          userFriendlyError = "Your YouTube cookies have expired or been rotated. Please open YouTube in your browser, export brand-new cookies, paste them in the Settings tab, and click Save.";
        } else if (cleanedStderr.includes("Sign in to confirm your age")) {
          userFriendlyError = "This playlist contains age-restricted videos and requires authentication.";
        } else if (cleanedStderr.includes("Unable to download webpage")) {
          userFriendlyError = "Network error or invalid link. Please try again.";
        } else if (cleanedStderr.includes("confirm you’re not a bot") || cleanedStderr.includes("confirm you're not a bot") || cleanedStderr.includes("Sign in to confirm")) {
          userFriendlyError = "YouTube is requesting verification to confirm you are not a bot. Please go to the Settings tab and paste your Netscape-format YouTube cookies to authenticate your requests.";
        }
        return res.status(500).json({ error: userFriendlyError, details: cleanedStderr });
      }

      try {
        const lines = stdoutData.trim().split("\n").filter(Boolean);
        if (lines.length === 0) {
          return res.status(404).json({ error: "No videos found in this URL/Playlist." });
        }

        // If the first line is valid JSON, check if it has multiple entries
        const entries = lines.map((line) => JSON.parse(line));
        const firstEntry = entries[0];

        const playlistTitle = firstEntry.playlist_title || firstEntry.playlist || "YouTube Playlist";
        const playlistId = firstEntry.playlist_id || "";

        const playlistVideos = entries.map((entry) => ({
          id: entry.id,
          title: entry.title,
          duration: entry.duration || 0,
          thumbnail: entry.thumbnails?.[0]?.url || `https://i.ytimg.com/vi/${entry.id}/hqdefault.jpg`,
          url: `https://www.youtube.com/watch?v=${entry.id}`,
          selected: true
        }));

        const metadata: VideoMetadata = {
          url,
          id: playlistId,
          title: playlistTitle,
          channel: firstEntry.playlist_uploader || "Various Artists",
          duration: playlistVideos.reduce((acc, v) => acc + v.duration, 0),
          thumbnail: playlistVideos[0]?.thumbnail || "",
          uploadDate: "Playlist",
          description: `YouTube playlist containing ${playlistVideos.length} videos.`,
          viewCount: 0,
          formats: [],
          subtitles: [],
          isPlaylist: true,
          playlistTitle,
          playlistVideos
        };

        res.json(metadata);
      } catch (e) {
        console.error("Playlist JSON parsing error:", e);
        res.status(500).json({ error: "Failed to parse playlist data.", details: e });
      }
    });
  };

  runPlaylistQuery(true);
});

// API: Trigger Download
app.post("/api/download", (req, res) => {
  const {
    id,
    url,
    title,
    thumbnail,
    type,
    resolution,
    format,
    subtitle,
    embedMetadata,
    embedThumbnail,
    downloadThumbnail
  } = req.body;

  if (!url || !id) {
    return res.status(400).json({ error: "Invalid download parameters." });
  }

  // Create active download item
  const settings = getSettings();
  const folder = settings.defaultFolder;
  const downloadItem: DownloadItem = {
    id,
    url,
    title,
    thumbnail,
    type,
    resolution,
    format,
    status: 'queued',
    progress: 0,
    speed: "Waiting...",
    eta: "--:--",
    downloadedSize: "0 B",
    totalSize: "Calculating...",
    remainingSize: "Calculating...",
    folder,
    date: new Date().toLocaleDateString(),
    subtitle: subtitle || 'none',
    embedMetadata: !!embedMetadata,
    embedThumbnail: !!embedThumbnail,
    downloadThumbnail: !!downloadThumbnail
  };

  activeDownloads.set(id, downloadItem);
  notifyProgressClients();

  // Function to actually run the spawned process
  const startProcess = (useCookies: boolean = true) => {
    downloadItem.status = 'downloading';
    downloadItem.speed = "0 B/s";
    notifyProgressClients();

    const args: string[] = [
      "--newline", 
      "--progress", 
      "--extractor-args", "youtube:player_client=android,mweb,web", 
      "--js-runtimes", "node",
      "--remote-components", "ejs:github",
      "--concurrent-fragments", "5", // Multi-threaded chunk downloads for super fast speeds
      "--retries", "infinite", // Automatic retry on network drops
      "--fragment-retries", "infinite" // Automatic fragment retry
    ];

    // Format selection
    if (type === 'audio') {
      if (resolution && resolution !== 'audio' && resolution !== 'best' && !resolution.endsWith('p')) {
        // Specific audio stream format ID selected
        args.push("-f", resolution);
      } else {
        args.push("-f", "bestaudio/best");
      }
      args.push("-x");
      const audioFormat = ['mp3', 'm4a', 'aac', 'wav', 'opus', 'flac'].includes(format) ? format : 'mp3';
      args.push("--audio-format", audioFormat);
      args.push("--audio-quality", "0"); // Force highest audio quality transcode (VBR 0 / CBR 320kbps)
    } else if (type === 'video_only') {
      if (resolution && resolution !== 'best' && !resolution.endsWith('p')) {
        // Specific video stream format ID selected
        args.push("-f", resolution);
      } else {
        const height = resolution.replace('p', '');
        if (height === 'best') {
          args.push("-f", "bestvideo/best");
        } else {
          args.push("-f", `bestvideo[height<=${height}]/best`);
        }
      }
      args.push("--merge-output-format", format);
    } else { // Video + Audio (combined)
      if (resolution && resolution !== 'best' && !resolution.endsWith('p')) {
        // Specific format ID or combination
        if (resolution.includes("+")) {
          args.push("-f", resolution);
        } else {
          // If they selected a single video format ID, merge with best audio
          args.push("-f", `${resolution}+bestaudio/best`);
        }
      } else {
        const height = resolution.replace('p', '');
        if (height === 'best') {
          args.push("-f", "bestvideo+bestaudio/best");
        } else {
          args.push("-f", `bestvideo[height<=${height}]+bestaudio/best[height<=${height}]/best`);
        }
      }
      args.push("--merge-output-format", format);
    }

    // Embed metadata if requested
    if (embedMetadata) {
      args.push("--embed-metadata");
    }

    // Embed thumbnail
    if (embedThumbnail) {
      args.push("--embed-thumbnail");
    }

    // Download separate thumbnail if requested
    if (downloadThumbnail) {
      args.push("--write-thumbnail");
    }

    // Subtitles support
    if (subtitle && subtitle !== 'none') {
      const lang = subtitle.replace(' (auto)', '');
      if (subtitle.endsWith('(auto)')) {
        args.push("--write-auto-subs");
      } else {
        args.push("--write-subs");
      }
      args.push("--sub-langs", lang);
    }

    // Output template
    const filenameTemplate = path.join(DOWNLOADS_DIR, `%(title)s-${id}.%(ext)s`);
    args.push("-o", filenameTemplate);

    // Proxy setting
    if (settings.proxy) {
      args.push("--proxy", settings.proxy);
    }

    if (useCookies && fs.existsSync(COOKIES_FILE)) {
      args.push("--cookies", COOKIES_FILE);
    }

    args.push(url);

    console.log("Spawning yt-dlp with args:", args.join(" "));
    const proc = spawn("yt-dlp", args, { env: { ...process.env, PYTHONWARNINGS: "ignore" } });
    activeProcesses.set(id, proc);

    let outputBuffer = "";
    let downloadHandled = false;

    proc.on("error", (err: any) => {
      if (downloadHandled) return;
      downloadHandled = true;
      console.error("yt-dlp download spawn error:", err);
      downloadItem.status = 'failed';
      downloadItem.speed = "Error";
      let errMsg = "Process failed. Please ensure yt-dlp is installed and in the system's PATH on the server.";
      if (err.code === "ENOENT") {
        errMsg = "The yt-dlp binary was not found. Serverless hosting platforms like Vercel do not support running CLI binaries or background Python processes like yt-dlp. Please deploy on Google Cloud Run, Railway, or Render.";
      }
      downloadItem.error = errMsg;
      notifyProgressClients();

      const history = getHistory();
      history.unshift({
        id,
        url,
        title,
        thumbnail,
        date: new Date().toLocaleDateString(),
        folder: DOWNLOADS_DIR,
        quality: resolution,
        format,
        status: 'failed',
        size: "0 B"
      });
      saveHistory(history);
    });

    proc.stdout.on("data", (data) => {
      const chunk = data.toString();
      outputBuffer += chunk;

      // Split by lines to parse progress
      const lines = chunk.split("\n");
      for (const line of lines) {
        if (!line.trim()) continue;

        // Parse merger status
        if (line.includes("[Merger]") || line.includes("Merging formats")) {
          downloadItem.progress = 98;
          downloadItem.speed = "Merging audio & video...";
          downloadItem.eta = "Finishing...";
          notifyProgressClients();
          continue;
        }

        // Parse extract audio / postprocessor status
        if (line.includes("[ExtractAudio]") || line.includes("Extracting audio")) {
          downloadItem.progress = 99;
          downloadItem.speed = "Extracting audio track...";
          downloadItem.eta = "Finishing...";
          notifyProgressClients();
          continue;
        }

        // Parse normal progress
        // Example: [download]  12.3% of  150.22MiB at  3.52MiB/s ETA 00:39
        if (line.includes("[download]")) {
          const percentMatch = line.match(/([\d\.]+)%/);
          const sizeMatch = line.match(/of\s+([0-9\.]+[a-zA-Z]+)/);
          const speedMatch = line.match(/at\s+([0-9\.]+[a-zA-Z]+\/s)/);
          const etaMatch = line.match(/ETA\s+([\d:]+)/);

          if (percentMatch) {
            downloadItem.progress = parseFloat(percentMatch[1]);
          }
          if (sizeMatch) {
            downloadItem.totalSize = sizeMatch[1];
          }
          
          // Compute downloaded size
          const downloadedSizeMatch = line.match(/\[download\]\s+([\d\.]+[a-zA-Z]+)\s+of/);
          if (downloadedSizeMatch) {
            downloadItem.downloadedSize = downloadedSizeMatch[1];
          } else if (percentMatch && sizeMatch) {
            const pct = parseFloat(percentMatch[1]) / 100;
            const totalStr = sizeMatch[1];
            const sizeVal = parseFloat(totalStr);
            const sizeUnit = totalStr.replace(/[\d\.]+/g, '').trim();
            downloadItem.downloadedSize = `${(sizeVal * pct).toFixed(1)} ${sizeUnit}`;
          }

          if (speedMatch) {
            downloadItem.speed = speedMatch[1];
          } else if (line.includes("has already been downloaded")) {
            downloadItem.progress = 100;
            downloadItem.speed = "Already downloaded";
            downloadItem.eta = "Completed";
            downloadItem.downloadedSize = downloadItem.totalSize;
          }
          if (etaMatch) {
            downloadItem.eta = etaMatch[1];
          }
          notifyProgressClients();
        }
      }
    });

    let stderrBuffer = "";

    proc.stderr.on("data", (data) => {
      const chunk = data.toString();
      stderrBuffer += chunk;
      console.error(`[Download stderr ${id}]:`, chunk);
    });

    proc.on("close", (code) => {
      if (downloadHandled) return;
      downloadHandled = true;
      activeProcesses.delete(id);
      
      if (code === 0) {
        downloadItem.status = 'completed';
        downloadItem.progress = 100;
        downloadItem.speed = "Done";
        downloadItem.eta = "00:00";
        notifyProgressClients();

        // Scan folder for downloaded files with matching ID to find the actual finalized path
        let filePath = "";
        try {
          const files = fs.readdirSync(DOWNLOADS_DIR);
          const matched = files.find(f => f.includes(`-${id}`));
          if (matched) {
            filePath = path.join(DOWNLOADS_DIR, matched);
          }
        } catch (e) {
          console.error("Error scanning output file:", e);
        }

        // Add to history
        const history = getHistory();
        const record: HistoryRecord = {
          id,
          url,
          title,
          thumbnail,
          date: new Date().toLocaleDateString(),
          folder: DOWNLOADS_DIR,
          quality: resolution,
          format,
          status: 'completed',
          size: downloadItem.totalSize || "Unknown Size"
        };
        history.unshift(record);
        saveHistory(history);

        // Keep active downloads in memory but mark as completed
        setTimeout(() => {
          activeDownloads.delete(id);
          notifyProgressClients();
        }, 10000); // clear active dashboard card after 10s

      } else {
        // Only mark as failed if it wasn't cancelled (processes that are paused/cancelled will handle their exit differently)
        if (downloadItem.status !== 'paused' && downloadItem.status !== 'queued') {
          const cleanedStderr = stderrBuffer
            .split("\n")
            .filter(line => !line.includes("Support for Python version 3.10 has been deprecated") && !line.includes("Deprecated Feature: Support for Python"))
            .join("\n")
            .trim();

          const isCookieInvalid = cleanedStderr.includes("cookies are no longer valid") || 
                                cleanedStderr.includes("The provided YouTube account cookies are no longer valid") ||
                                cleanedStderr.includes("rotated in the browser as a security measure");

          if (useCookies && isCookieInvalid) {
            console.warn(`[Self-Healing] Download ${id} failed due to expired/invalid YouTube cookies. Clearing cookies and retrying without cookies...`);
            
            try {
              if (fs.existsSync(COOKIES_FILE)) {
                fs.unlinkSync(COOKIES_FILE);
              }
            } catch (e) {}

            const currentSettings = getSettings();
            currentSettings.cookies = "";
            saveSettings(currentSettings);

            // Re-trigger download without cookies
            setTimeout(() => {
              startProcess(false);
            }, 1000);
            return;
          }

          downloadItem.status = 'failed';
          downloadItem.speed = "Error";
          
          let userFriendlyError = "Process failed. Quality might be unavailable or network cut.";
          
          if (cleanedStderr.includes("The page could not be found") || cleanedStderr.includes("NOT_FOUND") || cleanedStderr.includes("not found")) {
            userFriendlyError = "The requested video or playlist could not be found. Please check if the URL is correct and public.";
          } else if (isCookieInvalid) {
            userFriendlyError = "Your YouTube cookies have expired or been rotated. Please open YouTube in your browser, export brand-new cookies, paste them in the Settings tab, and click Save.";
          } else if (cleanedStderr.includes("confirm you’re not a bot") || cleanedStderr.includes("confirm you're not a bot") || cleanedStderr.includes("Sign in to confirm")) {
            userFriendlyError = "YouTube is requesting bot verification. Please go to the Settings tab and paste your Netscape-format YouTube cookies.";
          } else if (cleanedStderr.includes("Sign in to confirm your age")) {
            userFriendlyError = "This video is age-restricted and requires authentication via cookies in Settings.";
          } else if (cleanedStderr.includes("Private video")) {
            userFriendlyError = "This is a private video and cannot be downloaded.";
          } else if (cleanedStderr.includes("ffmpeg") || cleanedStderr.includes("ffprobe") || cleanedStderr.includes("Postprocessing: merger")) {
            userFriendlyError = "FFmpeg binary is missing or could not merge separate streams. Please install FFmpeg to support high-quality merges.";
          } else if (cleanedStderr.includes("No space left") || cleanedStderr.includes("Disk full") || cleanedStderr.includes("space") && cleanedStderr.includes("write")) {
            userFriendlyError = "Insufficient storage on the hosting environment or disk space full.";
          } else if (cleanedStderr.includes("Requested format is not available") || cleanedStderr.includes("unsupported") || cleanedStderr.includes("format not available")) {
            userFriendlyError = "The requested resolution or format combination is unavailable for this source video. Try choosing an alternative quality.";
          } else if (cleanedStderr.includes("HTTP Error 403") || cleanedStderr.includes("Sign in to confirm you’re not a bot")) {
            userFriendlyError = "YouTube has restricted this request (HTTP 403 / bot verification). Please configure fresh cookies in Settings.";
          } else if (cleanedStderr.includes("Network is unreachable") || cleanedStderr.includes("Connection reset") || cleanedStderr.includes("Timed out")) {
            userFriendlyError = "Network connection interrupted. The download will resume automatically when connectivity is restored.";
          }

          downloadItem.error = userFriendlyError;
          notifyProgressClients();

          // Save failed record in history
          const history = getHistory();
          history.unshift({
            id,
            url,
            title,
            thumbnail,
            date: new Date().toLocaleDateString(),
            folder: DOWNLOADS_DIR,
            quality: resolution,
            format,
            status: 'failed',
            size: "0 B"
          });
          saveHistory(history);
        }
      }
    });
  };

  // Immediate execution for now (respects queue limits depending on client control)
  const simultaneousCount = Array.from(activeDownloads.values()).filter(d => d.status === 'downloading').length;
  if (simultaneousCount >= settings.maxSimultaneousDownloads) {
    downloadItem.status = 'queued';
    downloadItem.speed = "Queued...";
    notifyProgressClients();
  } else {
    startProcess();
  }

  res.json({ success: true, item: downloadItem });
});

// API: Pause / Resume / Cancel Download Control
app.post("/api/download/control", (req, res) => {
  const { id, action } = req.body;
  const item = activeDownloads.get(id);
  const proc = activeProcesses.get(id);

  if (!item) {
    return res.status(404).json({ error: "Download item not found" });
  }

  if (action === 'pause') {
    if (proc) {
      proc.kill("SIGSTOP"); // Native OS pause
      item.status = 'paused';
      item.speed = "Paused";
      notifyProgressClients();
      return res.json({ success: true, status: "paused" });
    }
  } else if (action === 'resume') {
    if (proc) {
      proc.kill("SIGCONT"); // Native OS resume
      item.status = 'downloading';
      item.speed = "Resuming...";
      notifyProgressClients();
      return res.json({ success: true, status: "downloading" });
    } else {
      // If process exited or wasn't running, re-trigger download
      activeDownloads.delete(id);
      return res.json({ success: false, error: "Please retry the download." });
    }
  } else if (action === 'cancel') {
    if (proc) {
      proc.kill("SIGKILL"); // Native OS kill
    }
    activeProcesses.delete(id);
    activeDownloads.delete(id);
    notifyProgressClients();
    return res.json({ success: true, status: "cancelled" });
  }

  res.status(400).json({ error: "Invalid action" });
});

// API: Server-Sent Events for real-time progress stream
app.get("/api/download/progress", (req, res) => {
  res.setHeader("Content-Type", "text/event-stream");
  res.setHeader("Cache-Control", "no-cache");
  res.setHeader("Connection", "keep-alive");

  // Send initial payload
  res.write(`data: ${JSON.stringify(Array.from(activeDownloads.values()))}\n\n`);

  sseClients.push(res);

  req.on("close", () => {
    sseClients = sseClients.filter((client) => client !== res);
  });
});

// API: Stream downloaded files to the browser
app.get("/api/download/file", (req, res) => {
  const id = req.query.id as string;
  if (!id) {
    return res.status(400).send("ID is required.");
  }

  try {
    const files = fs.readdirSync(DOWNLOADS_DIR);
    const matched = files.find(f => f.includes(`-${id}`));
    if (!matched) {
      return res.status(404).send("Downloaded file not found. It might have been deleted or failed.");
    }

    const filePath = path.join(DOWNLOADS_DIR, matched);
    res.download(filePath, matched.replace(`-${id}`, ''));
  } catch (e) {
    res.status(500).send("Failed to retrieve file.");
  }
});

// API: AI Video Companion endpoint using Gemini
app.post("/api/ai/companion", async (req, res) => {
  const { url, title, description, message, chatHistory } = req.body;

  if (!message) {
    return res.status(400).json({ error: "Message is required" });
  }

  try {
    // Construct standard prompts
    const promptContents = [
      `You are YTDL Pro's AI Video Companion, a helpful AI expert deeply analyzing a YouTube video.
Current Video details:
- Title: "${title || 'Unknown Title'}"
- URL: ${url || 'Unknown URL'}
- Description: "${description || 'No description available'}"

Here is the conversation history so far:
${(chatHistory || []).map((m: any) => `${m.sender === 'user' ? 'User' : 'Assistant'}: ${m.text}`).join('\n')}

User's query: "${message}"

Please respond thoroughly. Use your high-reasoning capability (Thinking Mode is ENABLED) to give extremely accurate, detailed, and context-aware responses. Format with clean, responsive markdown. Keep formatting elegant.`
    ];

    const response = await ai.models.generateContent({
      model: "gemini-3.1-pro-preview",
      contents: promptContents,
      config: {
        thinkingConfig: {
          thinkingLevel: ThinkingLevel.HIGH,
        },
        systemInstruction: "You are YTDL Pro's professional AI companion. Provide deep insights, helpful answers, transcript summaries, and key learning points about the user's video.",
      },
    });

    res.json({ text: response.text });
  } catch (e: any) {
    console.error("Gemini API Error:", e);
    res.status(500).json({ error: "Gemini AI companion is currently unavailable. Ensure your API key is configured.", details: e.message });
  }
});

// Vite Middleware & SPA serving
async function startServer() {
  if (process.env.NODE_ENV !== "production" && !process.env.VERCEL) {
    const { createServer: createViteServer } = await import("vite");
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`[Server] Running YouTube Downloader at http://localhost:${PORT}`);
  });
}

if (!process.env.VERCEL) {
  startServer();
}

export default app;
